# Generated by Django 2.2 on 2019-04-28 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de Parution')),
                ('mode', models.IntegerField()),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cible', to=settings.AUTH_USER_MODEL)),
                ('profil_cible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='createur', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contenu',
            },
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('contenu_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reseau.Contenu')),
                ('commentaire_parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Parent', to='reseau.Contenu')),
            ],
            bases=('reseau.contenu',),
        ),
    ]
